[language-server.copilot]
command = "copilot"
args = ["--stdio"]

[language-server.pyright-langserver]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright-langserver.config]
python.analysis.autoSearchPaths = true
python.analysis.userLibraryCodeForTypes = true
python.analysis.diagnosticMode = "workspace"
python.linting.mypyEnabled = true

[language-server.ruff-lsp]
command = "ruff-lsp"
config = { settings = { args = [] } }

[[language]]
name = "python"
auto-format = true
language-servers =  ["pyright-langserver", "copilot", "ruff-lsp"]
formatter = { command = "black", args = ["-", "--quiet", "--line-length=89"]}
